// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Cursor struct {
	HasMore bool             `json:"hasMore"`
	Data    []WebhooksConfig `json:"data"`
}

func (c *Cursor) GetHasMore() bool {
	if c == nil {
		return false
	}
	return c.HasMore
}

func (c *Cursor) GetData() []WebhooksConfig {
	if c == nil {
		return []WebhooksConfig{}
	}
	return c.Data
}

type ConfigsResponse struct {
	Cursor Cursor `json:"cursor"`
}

func (c *ConfigsResponse) GetCursor() Cursor {
	if c == nil {
		return Cursor{}
	}
	return c.Cursor
}
