// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ConfigChangeSecret struct {
	Secret string `json:"secret"`
}

func (c *ConfigChangeSecret) GetSecret() string {
	if c == nil {
		return ""
	}
	return c.Secret
}
