// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ConfigUser struct {
	Endpoint   string   `json:"endpoint"`
	Secret     *string  `json:"secret,omitempty"`
	EventTypes []string `json:"eventTypes"`
}

func (c *ConfigUser) GetEndpoint() string {
	if c == nil {
		return ""
	}
	return c.Endpoint
}

func (c *ConfigUser) GetSecret() *string {
	if c == nil {
		return nil
	}
	return c.Secret
}

func (c *ConfigUser) GetEventTypes() []string {
	if c == nil {
		return []string{}
	}
	return c.EventTypes
}
