// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/webhooks/pkg/client/internal/utils"
)

type Security struct {
	ClientID     string `security:"scheme,type=oauth2,subtype=client_credentials,name=clientID"`
	ClientSecret string `security:"scheme,type=oauth2,subtype=client_credentials,name=clientSecret"`
	TokenURL     string `default:"/oauth/token"`
}

func (s Security) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Security) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"clientID", "clientSecret", "tokenURL"}); err != nil {
		return err
	}
	return nil
}

func (s *Security) GetClientID() string {
	if s == nil {
		return ""
	}
	return s.ClientID
}

func (s *Security) GetClientSecret() string {
	if s == nil {
		return ""
	}
	return s.ClientSecret
}

func (s *Security) GetTokenURL() string {
	if s == nil {
		return ""
	}
	return s.TokenURL
}
