// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/webhooks/pkg/client/models/components"
)

type ChangeConfigSecretRequest struct {
	// Config ID
	ID                 string                         `pathParam:"style=simple,explode=false,name=id"`
	ConfigChangeSecret *components.ConfigChangeSecret `request:"mediaType=application/json"`
}

func (c *ChangeConfigSecretRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *ChangeConfigSecretRequest) GetConfigChangeSecret() *components.ConfigChangeSecret {
	if c == nil {
		return nil
	}
	return c.ConfigChangeSecret
}

type ChangeConfigSecretResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Secret successfully changed.
	ConfigResponse *components.ConfigResponse
}

func (c *ChangeConfigSecretResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ChangeConfigSecretResponse) GetConfigResponse() *components.ConfigResponse {
	if c == nil {
		return nil
	}
	return c.ConfigResponse
}
