// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/webhooks/pkg/client/models/components"
)

type DeactivateConfigRequest struct {
	// Config ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeactivateConfigRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeactivateConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Config successfully deactivated.
	ConfigResponse *components.ConfigResponse
}

func (d *DeactivateConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeactivateConfigResponse) GetConfigResponse() *components.ConfigResponse {
	if d == nil {
		return nil
	}
	return d.ConfigResponse
}
