// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/webhooks/pkg/client/models/components"
)

type DeleteConfigRequest struct {
	// Config ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteConfigRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
