// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/webhooks/pkg/client/models/components"
)

type GetManyConfigsRequest struct {
	// Optional filter by Config ID
	ID *string `queryParam:"style=form,explode=true,name=id"`
	// Optional filter by endpoint URL
	Endpoint *string `queryParam:"style=form,explode=true,name=endpoint"`
}

func (g *GetManyConfigsRequest) GetID() *string {
	if g == nil {
		return nil
	}
	return g.ID
}

func (g *GetManyConfigsRequest) GetEndpoint() *string {
	if g == nil {
		return nil
	}
	return g.Endpoint
}

type GetManyConfigsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ConfigsResponse *components.ConfigsResponse
}

func (g *GetManyConfigsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetManyConfigsResponse) GetConfigsResponse() *components.ConfigsResponse {
	if g == nil {
		return nil
	}
	return g.ConfigsResponse
}
