// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/webhooks/pkg/client/models/components"
)

type InsertConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Config created successfully.
	ConfigResponse *components.ConfigResponse
}

func (i *InsertConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *InsertConfigResponse) GetConfigResponse() *components.ConfigResponse {
	if i == nil {
		return nil
	}
	return i.ConfigResponse
}
