// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/webhooks/pkg/client/models/components"
)

type UpdateConfigRequest struct {
	// Config ID
	ID         string                `pathParam:"style=simple,explode=false,name=id"`
	ConfigUser components.ConfigUser `request:"mediaType=application/json"`
}

func (u *UpdateConfigRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateConfigRequest) GetConfigUser() components.ConfigUser {
	if u == nil {
		return components.ConfigUser{}
	}
	return u.ConfigUser
}

type UpdateConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (u *UpdateConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}
